//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socialApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int FriendId { get; set; }
        public int MemberId { get; set; }
        public System.DateTime BecameFriend { get; set; }
        public bool IsFriend { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
