//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socialApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unlike
    {
        public int UnlikeId { get; set; }
        public int MemberID { get; set; }
        public int PostId { get; set; }
        public Nullable<bool> NotLiked { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
